"""Build original Ferris wheel, preserve editable source and export centimetre FBX."""
import hashlib
import json
import shutil
import sys
from pathlib import Path
import bpy
from mathutils import Matrix

HERE = Path(__file__).resolve().parent
sys.dont_write_bytecode = True
sys.path.insert(0, str(HERE))
import ferris_materials
import ferris_model

ROOT = HERE.parents[1]
BASE = ROOT / 'Assets/City'
OUT = BASE / 'Ferris'
QA = ROOT / 'Saved/QA/CityFerrisAssets'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path, data):
    path.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')


def main():
    assert bpy.app.version >= (5, 2, 0)
    print('BLENDER_VERSION', bpy.app.version_string, flush=True)
    for path in (OUT / 'Meshes', OUT / 'Sources/Generator', QA):
        path.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.read_factory_settings(use_empty=True)
    materials = ferris_materials.prepare(BASE, OUT)
    obj = ferris_model.build()
    bpy.context.view_layer.update()
    points = [obj.matrix_world @ vertex.co for vertex in obj.data.vertices]
    low = [round(min(p[i] for p in points) * 100, 4) for i in range(3)]
    high = [round(max(p[i] for p in points) * 100, 4) for i in range(3)]
    obj.data.calc_loop_triangles()
    record = dict(id='FerrisWheel', file='Ferris/Meshes/FerrisWheel.fbx',
                  boundsCm=dict(min=low, max=high, size=[high[i] - low[i] for i in range(3)]),
                  triangles=len(obj.data.loop_triangles), materialSlots=[m.name for m in obj.data.materials],
                  source='Original ANANTA procedural Ferris wheel', license='Original project asset',
                  triangleBudget=60000, origin='Ground centre XY', hubHeightCm=1835,
                  outerRadiusCm=1550, cabinCount=8,
                  lodRecommendation=dict(screenSizes=[1, .4, .16], triangleRatios=[1, .5, .22]))
    assert record['triangles'] <= 60000 and len(record['materialSlots']) <= 5, record
    assert abs(low[2]) < .01 and abs(high[2] - 3385) < .01 and high[0] - low[0] <= 1400, record
    bpy.ops.object.select_all(action='DESELECT')
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    obj.data.transform(Matrix.Scale(100, 4))
    bpy.context.scene.unit_settings.scale_length = .01
    bpy.ops.export_scene.fbx(filepath=str(BASE / record['file']), use_selection=True, object_types={'MESH'},
                             axis_forward='X', axis_up='Z', use_space_transform=True, global_scale=1,
                             apply_unit_scale=True, apply_scale_options='FBX_SCALE_UNITS',
                             bake_space_transform=False, mesh_smooth_type='FACE', use_tspace=True,
                             add_leaf_bones=False, bake_anim=False, path_mode='STRIP')
    obj.data.transform(Matrix.Scale(.01, 4))
    bpy.context.scene.unit_settings.scale_length = 1
    record['sha256'] = digest(BASE / record['file'])
    write_json(OUT / 'Sources/Provenance.json', dict(
        source='Original ANANTA geometry and deterministic 1K PBR pixels', license='Original project asset',
        thirdPartyAssets=[], authoring='Blender metres; FBX centimetres; wheel plane YZ',
        components='Twin continuous rims, tension spokes, rim truss, A frames, bearings, eight enclosed cabins',
        sourceEditing='Unhide Editable manufactured components to edit each manufactured part',
        limitations='Static ride. LODs generated by Unreal import. Runtime collision and GPU acceptance by root.'))
    for source in HERE.glob('ferris_*.py'):
        shutil.copy2(source, OUT / 'Sources/Generator' / source.name)
    for image in bpy.data.images:
        if image.filepath:
            image.filepath = bpy.path.relpath(image.filepath, start=str(OUT))
    bpy.context.preferences.filepaths.save_version = 0
    bpy.ops.wm.save_as_mainfile(filepath=str(OUT / 'FerrisWheel.blend'))
    sources = [dict(file=p.relative_to(BASE).as_posix(), sha256=digest(p),
                    source='Original ANANTA Ferris wheel source', license='Original project asset')
               for p in sorted(OUT.rglob('*')) if p.is_file() and 'Meshes' not in p.parts]
    write_json(BASE / 'ferris_manifest.json', dict(schemaVersion=1, units='cm', upAxis='Z',
               forwardAxis='X', meshes=[record], materials=materials, sourceFiles=sources))
    write_json(QA / 'build.json', dict(status='PASS', blender=bpy.app.version_string, mesh=record))
    print('RESULT ' + json.dumps(dict(status='PASS', triangles=record['triangles'], bounds=record['boundsCm'])))


if __name__ == '__main__':
    main()
